export default function CookiePolicy () {
    return (

<div class="font-sans-caption min-h-screen bg-gray-100 flex items-center justify-center pb-8 pt-8">
  <div class="containter mx-auto px-20">
    <div class="bg-white p-8 rounded-lg shadow-lg relative hover:shadow-2xl transition duration-500  ">
      <h1 class="text-4xl  font-extrabold text-center ">Izjava o kolačićima</h1>
      <h2 class=" text-2xl title-font font-medium text-gray-900 mt-4 mb-4">Uvod</h2>
        <p class="leading-relaxed mb-8 ">Prigodom korištenja ove internet stranice može pohraniti određene informacije putem kolačića (''cookie'') na računalo korisnika i time omogućava Internet stranici da vam prikaže informacije koje su prilagođene vašim potrebama. Ovaj dokument pruža detaljne informacije o uporabi kolačića i sličnih tehnologija, metodama upravljanja kolačićima te kako se koriste unutar internet stranica.</p>
        <h3 class=" text-2xl title-font font-medium text-gray-900 mt-4 mb-4">Što je to kolačić (cookie)?</h3>
        <p2 class="leading-relaxed mb-8">Kolačić (cookie) je mala brojčano-slovčana datoteka koja se sprema na korisničko računalo u trenutku kad pristupite određenim internet stranicama. Kolačići omogućavaju internet stranici prepoznavanje interesa korisnika prema onome što je korisnik prilikom povratka na stranicu odabirao. Kolačić sam po sebi ne sadrži niti ne prikuplja podatke. Međutim, kad ga poslužitelj pripremi u kombinaciji s internet preglednikom, on može pomoći internet stranici da isporuči korisniku prilagođeniju uslugu – primjerice, pamćenjem prethodnih kupovina ili pojedinosti o računu. Kolačići se nalaze u memoriji vašeg preglednika i svaki obično sadrži podatke kao što su npr. naziv poslužitelja s kojeg je kolačić poslan, vijek trajanja kolačića i vrijednost (obično slučajno generiran jedinstveni broj).</p2>
        <h4 class=" text-2xl title-font font-medium text-gray-900 mt-4 mb-4">Koje kolačiće koristimo i zašto?</h4>
        <p3 class="leading-relaxed mb-8">Mi koristimo kolačiće u svrhu oglašavanja vlastitih proizvoda i usluga te usluga i proizvoda svojih partnera koji bi korisnika mogli zanimati. Prikazivanje oglasa koje korisniku dostavlja ili partner omogućuje se putem kolačića odnosno treća strana može postaviti u Internet preglednik korisnika. Također upotrebljavamo kolačiće u svrhu mjerenje posjećenosti i oglašavanja proizvoda/usluga i to na samoj web stranici, na prikazivačkim mrežama i kroz korištenje ponovnog marketinga na usluzi Google Analytics. Upotrebom kolačića dobavljači treće strane (uključujući i Google). Posebno ističemo da možete isključiti usluge Google Analytics za oglašavanje na prikazivačkoj mreži i prilagoditi oglase za Google prikazivačku mrežu pomoću alata Upravitelj postavki oglasa. Također, u svrhu planiranja objava sadržaja primjerenih vašim interesima i budućih marketinških kampanja koristimo alat Google Analytics Demographics and Interest Reporting gdje možemo upotrebljavati podatke iz Googleova oglašavanja na temelju interesa ili podataka o publici treće strane (npr. dob, spol i interesi) na usluzi Google Analytics. Detaljne informacije treće strane o ovoj usluzi, kao i o mogućnostima korisnika da reguliraju postavke kolačića koji su za to nužni, dostupne su na linku. linku. Koristimo privremene kolačiće (''Session cookies'') i stalne kolačiće (''Persistent cookie''). Također, treba razlikovati kolačiće prve i kolačiće trećih strana. Privremeni kolačići ili kolačići sesije su kolačići koji se uklanjaju s računala po zatvaranju internet preglednika. Pomoću njih Internet stranice pohranjuju privremene podatke, poput stavki u košarici za kupnju. Stalni ili trajni kolačići su oni kolačići koji ostaju na računalu nakon zatvaranja internet preglednika. Pomoću njih Internet stranice pohranjuju podatke, kao što su ime za prijavu i lozinka, tako da se ne morate prijavljivati prilikom svakog posjeta određenim stranicama. Stalni kolačići mogu ostati na računalu danima, mjesecima, čak i godinama. Kolačići prve strane su kolačići koji dolaze s Internet stranice koje gledate, a mogu biti stalni ili privremeni. Pomoću tih kolačića Internet stranice mogu pohraniti podatke koje će ponovo koristiti prilikom sljedećeg posjeta toj Internet stranici. Kolačići trećih strana dolaze s reklama drugih Internet stranica (kao što su skočne ili druge reklame) koje se nalaze na Internet stranici koju trenutno gledate. Pomoću tih kolačića Internet stranice mogu pratiti vaše korištenje Interneta u marketinške svrhe.</p3>
        <h5 class=" text-2xl title-font font-medium text-gray-900 mt-4 mb-4">Dodatno o kolačićima</h5>
        <p4 class="leading-relaxed mb-8">Društvene mreže također mogu postavljati kolačiće na vaše računalo. To se događa na web stranicama koje Vam omogućavaju prijavu i registraciju preko računa društvenih mreža te ukoliko dijelite sadržaj web stranice na društvenim mrežama (npr. putem „Like" gumba). Konkretni utjecaj na vašu privatnost će se razlikovati od društvene mreže do društvenu mreže te ovisi o postavkama privatnosti koje ste izabrali na tim mrežama. Kako upravljati ovim kolačićima možete saznati na njihovim web stranicama. A1 će poštivati anonimnost i privatnost korisnika njegovih web stranica. A1 može prikupljati osobne podatke korisnika, kao što su npr. ime, adresa, telefonski broj ili e-mail adresa ako iste korisnik dobrovoljno dostavi A1 putem web stranice ili drugih kanala komunikacije. A1 će navedene podatke koristiti isključivo u svrhu što boljeg uvida i razumijevanja pojedinačnih potreba i zahtjeva korisnika kao i razvijanja mogućnosti što kvalitetnijeg pružanja svih usluga A1 na zadovoljstvo korisnika. A1 može za obradu podataka koristiti partnere s kojima ugovoriti odgovarajuću razinu zaštite podataka korisnika s time da A1 neće prosljeđivati partneru informaciju o kojem se konkretno korisniku radi.</p4> 
        <div>
        <img className="pt-12" src="/anaiblack.png" width="150" />
        </div>
    </div>
  </div>
</div>



    )
}